spring.application.name=cinelog

spring.datasource.url={jdbc URL here}
spring.datasource.username={username here}
spring.datasource.password={password here}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.cache.type=caffeine

tmdb.api.key={TMDB API key here}
tmdb.api.base-url=https://api.themoviedb.org/3
tmdb.api.image-base-url=https://image.tmdb.org/t/p/w500
tmdb.api.connect-timeout-ms=3000
tmdb.api.read-timeout-ms=5000

security.jwt.secret-key={32 chars secret key here}
security.jwt.access-token-expiration=900000
security.jwt.refresh-token-expiration=604800000
